version: "3.9"
services:
  #Direct the main healthcheck to port 8000
  main:
    build: .
    ports:
      - "8000:8000"
#Direct the face-bokeh to port 8001
  face-bokeh:
    build: ./face-bokeh
    ports:
      - "8001:8000"
#Direct the face-emotion to port 8002
  face-emotion:
    build: ./face-emotion
    ports:
      - "8002:8000"
  triton:
    image:  nvcr.io/nvidia/tritonserver:22.06-py3
    env_file:
      - .aws.env
    command:
      [
        "tritonserver",
        "--model-repository=s3://david-herman-ifueko-fourthbrain-session-1/models"
      ]
